# Generated by Django 3.1.6 on 2022-05-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('autor', models.CharField(blank=True, max_length=200, null=True)),
                ('completed_by', models.CharField(blank=True, default='me', max_length=200, null=True)),
                ('requested_by', models.EmailField(blank=True, default='me', max_length=200, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pedidos/pdfs/')),
                ('ip', models.CharField(blank=True, default='me', max_length=200, null=True)),
                ('votos', models.IntegerField(blank=True, default=0, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('also_wants', models.TextField(blank=True, max_length=5000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('unidecode_titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('unidecode_autor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
