# Generated by Django 3.1.6 on 2021-05-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='daydownloads',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
