# Generated by Django 3.1.6 on 2021-05-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210523_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='downloads',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
