# Generated by Django 3.1.6 on 2021-07-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='add_me_pedido',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='downloaded',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastdownload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='liked',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='pedidos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pedidos_liked',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pidio',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='viewed',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
